### ISSUE TITLE
Build System

### ISSUE THREAD

**Issue by dmccloskey** [dmccloskey/smartPeak_dependencies#1]
- [x] external cmake scripts for building all OpenMS dependencies and OpenMS
- [x] updated CMakeLists.txt script
- [x] refactor to use the ExternalProject module of cmake (https://cmake.org/cmake/help/v3.8/module/ExternalProject.html)
